[package]
name = "page-graph"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
lazy_static = "1.4.0"
petgraph = "0.6.0"
regex = "1.5.4"
reqwest = "0.11.4"
tempfile = "3.2.0"
tokio = { version = "1.10.0", features = ["full"] }
structopt = "0.3.22"
